language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=django==1.4.5
  - DJANGO=django==1.5
  - DJANGO=django==1.6
  - DJANGO=django==1.7
  - DJANGO='django>=1.8.a,<1.9'
  #- DJANGO=https://github.com/django/django/archive/stable/1.6.x.zip

matrix:
  exclude:
  - python: "3.3"
    env: DJANGO=django==1.4.5
  - python: "3.2"
    env: DJANGO=django==1.4.5
  - python: "2.6"
    env: DJANGO=django==1.7
  - python: "2.6"
    env: - DJANGO='django>=1.8.a,<1.9'

install:
  - pip install $DJANGO coverage==3.6

script:
  - coverage run --source=polymorphic runtests.py
  - coverage report -m

after_success:
  - pip install coveralls==0.2
  - coveralls

branches:
  only:
    - master
